# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # for automatic saving/restoring

set -g @continuum-restore 'on'
set -ga terminal-overrides ",xterm-256color:Tc"

# Initialize TMUX plugin manager (keep this line at the very bottom of the file)
run '~/.tmux/plugins/tpm/tpm'

set -g mode-keys vi
set -g mouse on

# remap prefix from 'C-b' to 'C-a'
# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set-option -g prefix C-b
bind-key C-b send-prefix

set -g extended-keys on

# Switch between panes using Alt/Meta + arrow keys and preserve zoom
bind-key -n M-Left if-shell -F "#{window_zoomed_flag}" 'select-pane -L ; resize-pane -Z' 'select-pane -L'
bind-key -n M-Right if-shell -F "#{window_zoomed_flag}" 'select-pane -R ; resize-pane -Z' 'select-pane -R'
bind-key -n M-Up if-shell -F "#{window_zoomed_flag}" 'select-pane -U ; resize-pane -Z' 'select-pane -U'
bind-key -n M-Down if-shell -F "#{window_zoomed_flag}" 'select-pane -D ; resize-pane -Z' 'select-pane -D'

