# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum' # for automatic saving/restoring

set -g @continuum-restore 'on'
set -ga terminal-overrides ",xterm-256color:Tc"

# Initialize TMUX plugin manager (keep this line at the very bottom of the file)
run '~/.tmux/plugins/tpm/tpm'

set -g mode-keys vi
set -g mouse on

# remap prefix from 'C-b' to 'C-a'
# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set-option -g prefix C-b
bind-key C-b send-prefix

set -g extended-keys on

# Reduce time tmux waits for after an ESC character (default is 500ms)
set -sg escape-time 10

# Allow tmux to distinguish between physical Alt and sequential Esc
set -ga terminal-overrides ',*:smcup@:rmcup@'

# To re-enumerate the windows indexes
set-option -g renumber-windows on

# Switch between panes using Ctrl + Alt/Meta + arrow keys and preserve zoom
bind-key -n C-M-Left if-shell -F "#{window_zoomed_flag}" 'select-pane -L ; resize-pane -Z' 'select-pane -L'
bind-key -n C-M-Right if-shell -F "#{window_zoomed_flag}" 'select-pane -R ; resize-pane -Z' 'select-pane -R'
bind-key -n C-M-Up if-shell -F "#{window_zoomed_flag}" 'select-pane -U ; resize-pane -Z' 'select-pane -U'
bind-key -n C-M-Down if-shell -F "#{window_zoomed_flag}" 'select-pane -D ; resize-pane -Z' 'select-pane -D'

# Switch between panes using prefix + arrow keys and preserve zoom
bind-key Left if-shell -F "#{window_zoomed_flag}" 'select-pane -L ; resize-pane -Z' 'select-pane -L'
bind-key Right if-shell -F "#{window_zoomed_flag}" 'select-pane -R ; resize-pane -Z' 'select-pane -R'
bind-key Up if-shell -F "#{window_zoomed_flag}" 'select-pane -U ; resize-pane -Z' 'select-pane -U'
bind-key Down if-shell -F "#{window_zoomed_flag}" 'select-pane -D ; resize-pane -Z' 'select-pane -D'
